"""Run a non-destructive runEDDB analysis for the Bz/SB hypothesis-2 set.

The script reuses the six completed PBE0-D3BJ/def2-TZVP/CPCM(Water)
wavefunctions generated by ``run_hypothesis2_validation.py``.  It performs no
ORCA SCF, geometry optimization, or frequency calculation.  Each GBW is copied
to an analysis-only directory, converted to ORCA JSON, and analysed over the
common N1--benzoyl fragment and its two para-directed conjugation pathways.
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import re
import shutil
import subprocess
import sys
from collections import deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


WORKSPACE = Path(__file__).resolve().parents[1]
if str(WORKSPACE) not in sys.path:
    sys.path.insert(0, str(WORKSPACE))

from molecule2fbx.comparison import (  # noqa: E402
    ExistingConformer,
    replace_terminal_tms_with_hydrogen,
    structural_descriptors,
)
from molecule2fbx.model import MoleculeModel  # noqa: E402
from run_hypothesis2_validation import conformers, load_pairs  # noqa: E402


SOURCE_ROOT = (
    WORKSPACE
    / "outputs"
    / "Bz_vs_SB_preliminary_comparison"
    / "hypothesis2_validation"
    / "pbe0_d3bj_def2_tzvp_cpcm_water"
)
OUTPUT_ROOT = (
    WORKSPACE
    / "outputs"
    / "Bz_vs_SB_preliminary_comparison"
    / "hypothesis2_validation"
    / "eddb"
    / "pbe0_d3bj_def2_tzvp_cpcm_water"
)
RUNEDDB = (
    WORKSPACE
    / "tools"
    / "runEDDB-2026-08-01"
    / "runEDDB_windows_x86_64"
    / "runEDDB.exe"
)
ORCA2JSON = Path(r"C:\ORCA_6.1.1\orca_2json.exe")
NCORES = 12


SUMMARY_RE = re.compile(
    r"Total\s+(ED|EDLB|EDDB)_([A-Z])\s+population:\s+"
    r"([-+0-9.Ee]+)\s+per atom:\s+([-+0-9.Ee]+)"
)
SELECTED_COUNT_RE = re.compile(r"Automatically selected NOBDs:\s+(\d+)")
SELECTED_LIST_RE = re.compile(r"List of automatically selected:\s+(.+)")
ATOM_ROW_RE = re.compile(
    r"^\s*(\d+)\s+([A-Z][a-z]?)\s+([+-]?\d+\.\d+)\s+"
    r"([+-]?\d+\.\d+)\s+\S+\s+\S+\s+([+-]?\d+\.\d+)\s+\S+\s+\S+\s*$"
)
BO_ROW_RE = re.compile(
    r"^\s*(\d+)\s+(\d+)~(\d+)\s+\S+\s+([+-]?\d+\.\d+)\s+(.+)$"
)
BO_COMPONENT_RE = re.compile(r"([+-]?\d+\.\d+)\(([^)]+)\)")


def now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    temporary.replace(path)


def run_command(command: list[str], cwd: Path, log_path: Path) -> str:
    process = subprocess.run(
        command,
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    output = process.stdout
    if process.stderr:
        output += "\n[stderr]\n" + process.stderr
    log_path.write_text(output, encoding="utf-8")
    if process.returncode != 0 or "Calculation completed" not in output:
        raise RuntimeError(
            f"Command failed ({process.returncode}); see {log_path}: {' '.join(command)}"
        )
    return output


def neighbours(model: MoleculeModel) -> dict[int, list[int]]:
    result = {index: [] for index in range(len(model.atoms))}
    for bond in model.bonds:
        result[bond.begin].append(bond.end)
        result[bond.end].append(bond.begin)
    return result


def shortest_distances(
    adjacency: dict[int, list[int]], start: int, allowed: set[int]
) -> dict[int, int]:
    distances = {start: 0}
    queue: deque[int] = deque([start])
    while queue:
        current = queue.popleft()
        for candidate in adjacency[current]:
            if candidate not in allowed or candidate in distances:
                continue
            distances[candidate] = distances[current] + 1
            queue.append(candidate)
    return distances


def simple_paths(
    adjacency: dict[int, list[int]], start: int, end: int, allowed: set[int]
) -> list[list[int]]:
    paths: list[list[int]] = []

    def visit(current: int, path: list[int]) -> None:
        if current == end:
            paths.append(path.copy())
            return
        for candidate in sorted(adjacency[current]):
            if candidate in allowed and candidate not in path:
                visit(candidate, [*path, candidate])

    visit(start, [start])
    return paths


def fragment_definition(model: MoleculeModel) -> dict[str, object]:
    structure = structural_descriptors(model)
    atom_indices = structure["atom_indices"]
    n = int(atom_indices["benzoyl_amide_n"])
    c = int(atom_indices["benzoyl_carbonyl_c"])
    o = int(atom_indices["benzoyl_carbonyl_o"])
    ipso = int(atom_indices["benzoyl_ipso_c"])
    adjacency = neighbours(model)

    ring: set[int] = set()
    queue: deque[int] = deque([ipso])
    while queue:
        current = queue.popleft()
        if current in ring:
            continue
        ring.add(current)
        for candidate in adjacency[current]:
            if candidate == c:
                continue
            if model.atoms[candidate].element.casefold() == "c" and candidate not in ring:
                queue.append(candidate)
    if len(ring) != 6:
        raise RuntimeError(f"Expected a six-carbon benzoyl ring, found {sorted(ring)}")

    distances = shortest_distances(adjacency, ipso, ring)
    para_candidates = [index for index, distance in distances.items() if distance == 3]
    if len(para_candidates) != 1:
        raise RuntimeError(f"Could not identify a unique para carbon: {distances}")
    para = para_candidates[0]
    ring_paths = [path for path in simple_paths(adjacency, ipso, para, ring) if len(path) == 4]
    if len(ring_paths) != 2:
        raise RuntimeError(f"Expected two ipso-to-para ring paths, found {ring_paths}")
    ring_paths.sort(key=lambda path: path[1])

    role_by_index = {
        n: "amide_n",
        c: "carbonyl_c",
        o: "carbonyl_o",
        ipso: "ring_ipso",
        ring_paths[0][1]: "ring_ortho_a",
        ring_paths[0][2]: "ring_meta_a",
        para: "ring_para",
        ring_paths[1][2]: "ring_meta_b",
        ring_paths[1][1]: "ring_ortho_b",
    }
    if len(role_by_index) != 9:
        raise RuntimeError(f"Fragment atom roles are not unique: {role_by_index}")

    pathways = {
        "amide_side_a": [n, c, *ring_paths[0]],
        "amide_side_b": [n, c, *ring_paths[1]],
        "oxygen_side_a": [o, c, *ring_paths[0]],
        "oxygen_side_b": [o, c, *ring_paths[1]],
    }
    direct_bonds = {
        "amide_n_carbonyl_c": tuple(sorted((n, c))),
        "carbonyl_c_o": tuple(sorted((c, o))),
        "carbonyl_c_ring_ipso": tuple(sorted((c, ipso))),
    }
    for side, path in (("a", ring_paths[0]), ("b", ring_paths[1])):
        for position, (first, second) in enumerate(zip(path, path[1:]), start=1):
            direct_bonds[f"ring_{side}_{position}"] = tuple(sorted((first, second)))

    return {
        "fragment_indices_zero_based": sorted(role_by_index),
        "fragment_indices_one_based": [index + 1 for index in sorted(role_by_index)],
        "role_by_zero_based_index": {str(index): role for index, role in role_by_index.items()},
        "role_to_one_based_index": {role: index + 1 for index, role in role_by_index.items()},
        "pathways_zero_based": pathways,
        "pathways_one_based": {
            name: [index + 1 for index in path] for name, path in pathways.items()
        },
        "direct_bonds_zero_based": {
            name: list(pair) for name, pair in direct_bonds.items()
        },
        "direct_bonds_one_based": {
            name: [pair[0] + 1, pair[1] + 1] for name, pair in direct_bonds.items()
        },
    }


def compact_index_list(indices: Iterable[int]) -> str:
    return ",".join(str(index) for index in indices)


def pathway_string(indices: Iterable[int]) -> str:
    return "-".join(str(index) for index in indices)


def parse_runeddb(output: str) -> dict[str, object]:
    summary: dict[str, dict[str, float]] = {}
    for density, scope, total, per_atom in SUMMARY_RE.findall(output):
        summary[density.lower()] = {
            "scope": scope,
            "total": float(total),
            "per_atom": float(per_atom),
        }

    atoms: dict[int, dict[str, object]] = {}
    for line in output.splitlines():
        match = ATOM_ROW_RE.match(line)
        if match:
            atoms[int(match.group(1))] = {
                "element": match.group(2),
                "natural_charge": float(match.group(3)),
                "electron_population": float(match.group(4)),
                "eddb_population": float(match.group(5)),
            }

    bond_orders: dict[str, dict[str, object]] = {}
    for line in output.splitlines():
        match = BO_ROW_RE.match(line)
        if not match:
            continue
        first = int(match.group(2))
        second = int(match.group(3))
        components = [
            {"occupation": float(value), "symmetry": symmetry}
            for value, symmetry in BO_COMPONENT_RE.findall(match.group(5))
        ]
        bond_orders[f"{min(first, second)}-{max(first, second)}"] = {
            "total_wiberg": float(match.group(4)),
            "pi_component_sum": sum(
                float(component["occupation"])
                for component in components
                if component["symmetry"] == "π"
            ),
            "sigma_component_sum": sum(
                float(component["occupation"])
                for component in components
                if component["symmetry"] == "σ"
            ),
            "components": components,
        }

    selected_count = SELECTED_COUNT_RE.search(output)
    selected_list = SELECTED_LIST_RE.search(output)
    return {
        "summary": summary,
        "atoms_one_based": {str(index): value for index, value in atoms.items()},
        "bond_orders_one_based": bond_orders,
        "auto_pi_selected_count": int(selected_count.group(1)) if selected_count else None,
        "auto_pi_selected_list": selected_list.group(1).strip() if selected_list else None,
        "completed": "Calculation completed" in output,
        "warning_count": output.count("WARNING"),
    }


def validate_json_atom_order(json_path: Path, model: MoleculeModel) -> None:
    payload = json.loads(json_path.read_text(encoding="utf-8"))
    atoms = payload["Molecule"]["Atoms"]
    actual = [str(atom["ElementLabel"]) for atom in atoms]
    expected = [atom.element for atom in model.atoms]
    if actual != expected:
        raise RuntimeError(
            f"ORCA JSON atom ordering differs from MoleculeModel for {json_path}"
        )


def prepare_json(source_dir: Path, destination: Path, model: MoleculeModel) -> Path:
    destination.mkdir(parents=True, exist_ok=True)
    source_gbw = source_dir / "property.gbw"
    if not source_gbw.is_file():
        raise RuntimeError(f"Missing source GBW: {source_gbw}")
    target_gbw = destination / "wavefunction.gbw"
    if not target_gbw.is_file() or target_gbw.stat().st_size != source_gbw.stat().st_size:
        shutil.copy2(source_gbw, target_gbw)
    for suffix in ("densities", "densitiesinfo"):
        source = source_dir / f"property.{suffix}"
        target = destination / f"wavefunction.{suffix}"
        if source.is_file() and (
            not target.is_file() or target.stat().st_size != source.stat().st_size
        ):
            shutil.copy2(source, target)

    json_path = destination / "wavefunction.json"
    if not json_path.is_file():
        process = subprocess.run(
            [str(ORCA2JSON), target_gbw.name, "-json"],
            cwd=destination,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        (destination / "orca_2json.log").write_text(
            process.stdout + ("\n[stderr]\n" + process.stderr if process.stderr else ""),
            encoding="utf-8",
        )
        if process.returncode != 0 or not json_path.is_file():
            raise RuntimeError(f"orca_2json failed for {target_gbw}")
    validate_json_atom_order(json_path, model)
    return json_path


def run_analysis(
    *,
    json_path: Path,
    job_dir: Path,
    fragment: dict[str, object],
    name: str,
    extra: list[str],
    table: str | None = None,
) -> dict[str, object]:
    fragment_arg = compact_index_list(fragment["fragment_indices_one_based"])
    command = [
        str(RUNEDDB),
        "--input",
        json_path.name,
        "--fragment",
        fragment_arg,
        "--basis",
        "nvb",
        "--ncores",
        str(NCORES),
        *extra,
    ]
    if table:
        command.extend(["--table", table, "--verbose"])
    else:
        command.append("--quiet")
    log_path = job_dir / f"{name}.log"
    if log_path.is_file() and "Calculation completed" in log_path.read_text(
        encoding="utf-8", errors="replace"
    ):
        output = log_path.read_text(encoding="utf-8", errors="replace")
    else:
        output = run_command(command, job_dir, log_path)
    parsed = parse_runeddb(output)
    parsed["log"] = str(log_path.resolve())
    parsed["command"] = command
    return parsed


def run_pathways(
    json_path: Path, job_dir: Path, fragment: dict[str, object]
) -> dict[str, object]:
    result: dict[str, object] = {}
    pathways = fragment["pathways_one_based"]
    for name, indices in pathways.items():
        command = [
            str(RUNEDDB),
            "--input",
            json_path.name,
            "--pathway",
            pathway_string(indices),
            "--basis",
            "nvb",
            "--auto-pi",
            "--ncores",
            str(NCORES),
            "--quiet",
        ]
        log_path = job_dir / f"pathway_{name}_pi_frozen.log"
        if log_path.is_file() and "Calculation completed" in log_path.read_text(
            encoding="utf-8", errors="replace"
        ):
            output = log_path.read_text(encoding="utf-8", errors="replace")
        else:
            output = run_command(command, job_dir, log_path)
        parsed = parse_runeddb(output)
        parsed["indices_one_based"] = indices
        parsed["log"] = str(log_path.resolve())
        result[name] = parsed
    return result


def atom_roles(
    parsed: dict[str, object], fragment: dict[str, object]
) -> dict[str, dict[str, object]]:
    atoms = parsed["atoms_one_based"]
    return {
        role: atoms[str(index)]
        for role, index in fragment["role_to_one_based_index"].items()
    }


def bond_roles(
    parsed: dict[str, object], fragment: dict[str, object]
) -> dict[str, dict[str, object]]:
    bonds = parsed["bond_orders_one_based"]
    result: dict[str, dict[str, object]] = {}
    for role, pair in fragment["direct_bonds_one_based"].items():
        key = f"{min(pair)}-{max(pair)}"
        if key not in bonds:
            raise RuntimeError(f"runEDDB did not report expected bond {role}: {key}")
        result[role] = bonds[key]
    return result


def model_records() -> list[dict[str, object]]:
    pairs = load_pairs()
    bz_by_id, sb_by_id = conformers()
    records: list[dict[str, object]] = []
    for pair_number, pair in enumerate(pairs, start=1):
        pair_id = f"pair{pair_number:03d}"
        bz: ExistingConformer = bz_by_id[str(pair["first_conformer_id"])]
        sb: ExistingConformer = sb_by_id[str(pair["second_conformer_id"])]
        records.extend(
            [
                {
                    "pair_id": pair_id,
                    "species": "bz_optimized",
                    "conformer_id": str(bz.entry["conformer_id"]),
                    "model": bz.model,
                },
                {
                    "pair_id": pair_id,
                    "species": "sb_optimized",
                    "conformer_id": str(sb.entry["conformer_id"]),
                    "model": sb.model,
                },
                {
                    "pair_id": pair_id,
                    "species": "sb_tms_to_h_fixed",
                    "conformer_id": str(sb.entry["conformer_id"]),
                    "model": replace_terminal_tms_with_hydrogen(sb.model),
                },
            ]
        )
    return records


def run_cube_exports(records: list[dict[str, object]]) -> list[dict[str, object]]:
    results: list[dict[str, object]] = []
    by_pair_species = {
        (str(record["pair_id"]), str(record["species"])): record for record in records
    }
    for pair_id in sorted({str(record["pair_id"]) for record in records}):
        reference = by_pair_species[(pair_id, "sb_tms_to_h_fixed")]
        perturbed = by_pair_species[(pair_id, "sb_optimized")]
        cube_dir = OUTPUT_ROOT / pair_id / "fixed_tms_minus_h_cubes"
        cube_dir.mkdir(parents=True, exist_ok=True)
        ref_fragment = reference["fragment"]
        sb_fragment = perturbed["fragment"]
        ref_json = Path(reference["json"])
        sb_json = Path(perturbed["json"])

        ref_prefix = "detms_reference"
        ref_command = [
            str(RUNEDDB),
            "--input",
            str(ref_json),
            "--fragment",
            compact_index_list(ref_fragment["fragment_indices_one_based"]),
            "--basis",
            "nvb",
            "--auto-pi",
            "--export-cube",
            "eddb,bdf",
            "--cube-size",
            "120",
            "--ncores",
            str(NCORES),
            "--out-prefix",
            ref_prefix,
            "--quiet",
        ]
        ref_log = cube_dir / "detms_reference_export.log"
        eddb_reference = cube_dir / f"{ref_prefix}.EDDB_F.cube"
        bdf_reference = cube_dir / f"{ref_prefix}.BDF_F.cube"
        if not (
            eddb_reference.is_file()
            and bdf_reference.is_file()
            and ref_log.is_file()
            and "Calculation completed"
            in ref_log.read_text(encoding="utf-8", errors="replace")
        ):
            run_command(ref_command, cube_dir, ref_log)
        if not eddb_reference.is_file() or not bdf_reference.is_file():
            raise RuntimeError(f"Missing reference cubes in {cube_dir}")

        differential_files: dict[str, str] = {}
        for token, reference_cube in (
            ("deddb", eddb_reference),
            ("dbdf", bdf_reference),
        ):
            prefix = f"sb_minus_detms_{token}"
            command = [
                str(RUNEDDB),
                "--input",
                str(sb_json),
                "--fragment",
                compact_index_list(sb_fragment["fragment_indices_one_based"]),
                "--basis",
                "nvb",
                "--auto-pi",
                "--export-cube",
                token,
                "--cube-ref",
                str(reference_cube),
                "--ncores",
                str(NCORES),
                "--out-prefix",
                prefix,
                "--quiet",
            ]
            log_path = cube_dir / f"{prefix}.log"
            suffix = "DEDDB_F.cube" if token == "deddb" else "DBDF_F.cube"
            output_cube = cube_dir / f"{prefix}.{suffix}"
            if not (
                output_cube.is_file()
                and log_path.is_file()
                and "Calculation completed"
                in log_path.read_text(encoding="utf-8", errors="replace")
            ):
                run_command(command, cube_dir, log_path)
            if not output_cube.is_file():
                raise RuntimeError(f"Missing differential cube: {output_cube}")
            differential_files[token] = str(output_cube.resolve())
        results.append(
            {
                "pair_id": pair_id,
                "comparison": "sb_optimized_minus_sb_tms_to_h_fixed",
                "scope": "common_benzoyl_amide_fragment",
                "pi_selection": "auto-pi",
                "pi_selection_consistent": False,
                "selection_warning": (
                    "de-TMS selected seven pi-NOBDs while SB selected six. The omitted "
                    "SB tail has about 0.0002e occupancy and does not change the scalar "
                    "EDDB total at five decimals; maps are supporting, not primary evidence."
                ),
                "reference_eddb_cube": str(eddb_reference.resolve()),
                "reference_bdf_cube": str(bdf_reference.resolve()),
                "differential_cubes": differential_files,
            }
        )
    return results


def delta(first: float | None, second: float | None) -> float | None:
    if first is None or second is None:
        return None
    return float(first) - float(second)


def nested_metric(record: dict[str, object], path: tuple[str, ...]) -> float | None:
    value: object = record
    for key in path:
        if not isinstance(value, dict) or key not in value:
            return None
        value = value[key]
    return float(value) if isinstance(value, (int, float)) else None


def build_comparisons(records: list[dict[str, object]]) -> dict[str, object]:
    metrics: dict[str, tuple[str, ...]] = {
        "fragment_all_eddb": ("fragment_all_frozen", "summary", "eddb", "total"),
        "fragment_pi_eddb_frozen": (
            "fragment_pi_frozen",
            "summary",
            "eddb",
            "total",
        ),
        "fragment_pi_eddb_rigorous": (
            "fragment_pi_rigorous",
            "summary",
            "eddb",
            "total",
        ),
        "fragment_pi_eddb_manual_matched": (
            "fragment_pi_manual_matched",
            "summary",
            "eddb",
            "total",
        ),
    }
    for role in (
        "amide_n",
        "carbonyl_c",
        "carbonyl_o",
        "ring_ipso",
        "ring_ortho_a",
        "ring_meta_a",
        "ring_para",
        "ring_meta_b",
        "ring_ortho_b",
    ):
        metrics[f"pi_eddb_atom_{role}"] = (
            "fragment_pi_frozen",
            "atoms_by_role",
            role,
            "eddb_population",
        )
        metrics[f"npa_charge_{role}"] = (
            "fragment_pi_frozen",
            "atoms_by_role",
            role,
            "natural_charge",
        )
    for role in (
        "amide_n_carbonyl_c",
        "carbonyl_c_o",
        "carbonyl_c_ring_ipso",
    ):
        metrics[f"wiberg_{role}"] = (
            "fragment_all_frozen",
            "bonds_by_role",
            role,
            "total_wiberg",
        )
        metrics[f"pi_boo_{role}"] = (
            "fragment_all_frozen",
            "bonds_by_role",
            role,
            "pi_component_sum",
        )
    for path_name in (
        "amide_side_a",
        "amide_side_b",
        "oxygen_side_a",
        "oxygen_side_b",
    ):
        metrics[f"pathway_pi_eddb_{path_name}"] = (
            "pathways_pi_frozen",
            path_name,
            "summary",
            "eddb",
            "total",
        )

    by_pair_species = {
        (str(record["pair_id"]), str(record["species"])): record for record in records
    }
    comparisons: list[dict[str, object]] = []
    definitions = {
        "optimized_sb_minus_bz": ("sb_optimized", "bz_optimized"),
        "fixed_geometry_tms_minus_h": ("sb_optimized", "sb_tms_to_h_fixed"),
        "geometry_residual_detms_minus_bz": (
            "sb_tms_to_h_fixed",
            "bz_optimized",
        ),
    }
    for pair_id in sorted({str(record["pair_id"]) for record in records}):
        for comparison_name, (first_species, second_species) in definitions.items():
            first = by_pair_species[(pair_id, first_species)]
            second = by_pair_species[(pair_id, second_species)]
            values = {
                metric: delta(nested_metric(first, path), nested_metric(second, path))
                for metric, path in metrics.items()
            }
            comparisons.append(
                {
                    "pair_id": pair_id,
                    "comparison": comparison_name,
                    "first_species": first_species,
                    "second_species": second_species,
                    "deltas_first_minus_second": values,
                }
            )

    fixed = [
        item for item in comparisons if item["comparison"] == "fixed_geometry_tms_minus_h"
    ]
    robustness: dict[str, object] = {}
    for metric in metrics:
        values = [item["deltas_first_minus_second"][metric] for item in fixed]
        numeric = [float(value) for value in values if value is not None]
        signs = [0 if value == 0 else (1 if value > 0 else -1) for value in numeric]
        robustness[metric] = {
            "fixed_tms_minus_h_values": numeric,
            "mean": sum(numeric) / len(numeric) if numeric else None,
            "same_nonzero_sign_across_pairs": bool(numeric)
            and all(sign == signs[0] and sign != 0 for sign in signs),
        }
    return {
        "delta_definitions": {
            "optimized_sb_minus_bz": "optimized SB minus matched optimized Bz",
            "fixed_geometry_tms_minus_h": (
                "SB minus de-TMS/H at identical common-atom coordinates"
            ),
            "geometry_residual_detms_minus_bz": (
                "de-TMS/H at SB geometry minus matched optimized Bz"
            ),
        },
        "comparisons": comparisons,
        "fixed_geometry_robustness": robustness,
    }


def write_comparison_csv(payload: dict[str, object]) -> None:
    rows = []
    for comparison in payload["comparisons"]:
        for metric, value in comparison["deltas_first_minus_second"].items():
            rows.append(
                {
                    "pair_id": comparison["pair_id"],
                    "comparison": comparison["comparison"],
                    "metric": metric,
                    "delta_first_minus_second": value,
                }
            )
    path = OUTPUT_ROOT / "paired_deltas.csv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    if not RUNEDDB.is_file():
        raise SystemExit(f"runEDDB executable not found: {RUNEDDB}")
    if not ORCA2JSON.is_file():
        raise SystemExit(f"orca_2json executable not found: {ORCA2JSON}")

    records = model_records()
    completed: list[dict[str, object]] = []
    for record in records:
        pair_id = str(record["pair_id"])
        species = str(record["species"])
        model: MoleculeModel = record.pop("model")
        source_dir = SOURCE_ROOT / pair_id / species
        job_dir = OUTPUT_ROOT / pair_id / species
        json_path = prepare_json(source_dir, job_dir, model)
        fragment = fragment_definition(model)

        all_frozen = run_analysis(
            json_path=json_path,
            job_dir=job_dir,
            fragment=fragment,
            name="fragment_all_frozen",
            extra=[],
            table="bo,npa",
        )
        all_frozen["atoms_by_role"] = atom_roles(all_frozen, fragment)
        all_frozen["bonds_by_role"] = bond_roles(all_frozen, fragment)
        pi_frozen = run_analysis(
            json_path=json_path,
            job_dir=job_dir,
            fragment=fragment,
            name="fragment_pi_frozen",
            extra=["--auto-pi"],
            table="nobd,npa",
        )
        pi_frozen["atoms_by_role"] = atom_roles(pi_frozen, fragment)
        pi_rigorous = run_analysis(
            json_path=json_path,
            job_dir=job_dir,
            fragment=fragment,
            name="fragment_pi_rigorous",
            extra=["--auto-pi", "--nao-algorithm", "rigorous"],
            table="nobd,npa",
        )
        pi_rigorous["atoms_by_role"] = atom_roles(pi_rigorous, fragment)
        if species == "sb_optimized":
            manual_pi_selection = "1:5,25,28"
        else:
            manual_pi_selection = "1:5,24,27"
        pi_manual = run_analysis(
            json_path=json_path,
            job_dir=job_dir,
            fragment=fragment,
            name="fragment_pi_manual_matched",
            extra=["--select-nobd", manual_pi_selection],
            table="nobd,npa",
        )
        pi_manual["atoms_by_role"] = atom_roles(pi_manual, fragment)
        pi_manual["manual_selection"] = manual_pi_selection
        pathways = run_pathways(json_path, job_dir, fragment)

        completed.append(
            {
                **record,
                "source_gbw": str((source_dir / "property.gbw").resolve()),
                "json": str(json_path.resolve()),
                "fragment": fragment,
                "fragment_all_frozen": all_frozen,
                "fragment_pi_frozen": pi_frozen,
                "fragment_pi_rigorous": pi_rigorous,
                "fragment_pi_manual_matched": pi_manual,
                "pathways_pi_frozen": pathways,
            }
        )
        print(f"completed {pair_id} {species}", flush=True)

    cube_results = run_cube_exports(completed)
    comparisons = build_comparisons(completed)
    runeddb_hash = hashlib.sha256(RUNEDDB.read_bytes()).hexdigest().upper()
    payload = {
        "generated_at_utc": now(),
        "status": "SUCCESS",
        "purpose": (
            "Test whether the small fixed-geometry TMS electronic effect is expressed "
            "as a reproducible change in benzoyl-amide electron delocalization."
        ),
        "new_orca_calculations": 0,
        "source_condition": "PBE0-D3BJ/def2-TZVP/CPCM(Water)",
        "runeddb_executable": str(RUNEDDB.resolve()),
        "runeddb_sha256": runeddb_hash,
        "analysis_defaults": {
            "basis": "NVB",
            "nao_algorithm_primary": "frozen-nmb",
            "nao_algorithm_sensitivity": "rigorous (NBO7-style)",
            "pi_selection": "auto-pi, with selected counts/lists retained",
            "pi_selection_control": (
                "matched seven-orbital manual selections retained separately"
            ),
            "scope": "common N1-carbonyl-benzoyl nine-atom fragment",
            "ncores": NCORES,
        },
        "records": completed,
        "fixed_geometry_differential_maps": cube_results,
        **comparisons,
        "interpretation_limits": {
            "not_nbo_e2": (
                "EDDB/NOBD populations are not NBO second-order perturbation energies."
            ),
            "not_a_barrier": (
                "Delocalization changes are ground-state descriptors, not hydrolysis "
                "activation energies or metabolic rates."
            ),
            "auto_pi_warning": (
                "Differential BDF maps require comparable pi-NOBD selections; full "
                "fragment EDDB and matched-manual scalar populations are the primary result."
            ),
        },
    }
    write_json(OUTPUT_ROOT / "results.json", payload)
    write_comparison_csv(comparisons)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
